repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
-   repo: https://github.com/pycqa/isort
    rev: ''
    hooks:
        - id: isort